export const SET_CURRENT_STEP = 'SET_CURRENT_STEP';
export const SET_ALL_INPUT_VALUES_ON_REGISTER =
  'SET_ALL_INPUT_VALUES_ON_REGISTER';
export const SET_PLAN = 'SET_PLAN';
export const SET_REGISTER_IS_VALID = 'SET_REGISTER_IS_VALID';
